apiVersion: apps/v1
kind: Deployment
metadata:
   name: ecom-deployment
spec:
   replicas: 3
   selector: 
      matchLabels: 
        app.kubernetes.io/name: ecom    
   template: 
     metadata: 
      labels: 
        app.kubernetes.io/name: ecom
     spec:
      containers:
        - name: ecom-container 
          image: chetansingh673/multibranch-flask-app:build-17
          ports:
            - containerPort: 5000         
