pipeline {
    agent any

     tools {
        jdk 'jdk21'
    }

    options {
        disableConcurrentBuilds()
    }

    environment {
        IMAGE_NAME = "chetansingh673/multibranch-flask-app"
        SCANNER_HOME = tool 'sonar-scanner' 
    }
    
    stages {
        stage("Clean Workspace") {
            steps {
                cleanWs()
            }
        }

        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ChetanSingh673/multibranch_pipeline_ecommerce.git'
            }
        }

        stage("SonarQube Analysis") {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh ''' $SCANNER_HOME/bin/sonar-scanner \
                        -Dsonar.projectName=Ecommerce \
                        -Dsonar.projectKey=Ecommerce '''
                }
            }
        }

        stage("Quality Gate") {
            steps {
                script {
                    timeout(time: 3, unit: 'MINUTES') {
                        waitForQualityGate abortPipeline: false, credentialsId: 'sonar-token'
                    }
                }
            }
        }
        
        stage("Trivy File Scan") {
            steps {
                sh "trivy fs . > trivyfs.txt"
            }
        }
        
        stage('Build and Push Image') {
            when { branch 'main' }
            steps {
                script {
                    env.IMAGE_TAG = "build-${BUILD_NUMBER}"

                    withCredentials([string(credentialsId: 'dockerhub-creds', variable: 'dockerpwd')]) {                       
                        sh """
                        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} main_branch_code
                        echo "$dockerpwd" | docker login -u chetansingh673 --password-stdin
                        docker push ${IMAGE_NAME}:${IMAGE_TAG}
                        """
                    }
                }
            }
        }

        stage("Trivy Scan Image") {
            steps {
                script {
                    sh """
                    echo "🔍 Running Trivy scan on ${IMAGE_NAME}:${IMAGE_TAG}"

                    # JSON report
                    trivy image -f json -o trivy-image.json ${IMAGE_NAME}:${IMAGE_TAG}
                    # HTML report using built-in HTML format
                    trivy image -f table -o trivy-image.txt ${IMAGE_NAME}:${IMAGE_TAG}

                    # Fail build if HIGH/CRITICAL vulnerabilities found
                    # trivy image --exit-code 1 --severity HIGH,CRITICAL ${IMAGE_NAME}:${IMAGE_TAG} || true
                    """
                }
            }
        }

        stage('Update K8s Manifest') {
            when { branch 'main' }
            steps {
                script {
                    withCredentials([usernamePassword(
                        credentialsId: 'github-creds',
                        usernameVariable: 'GIT_USERNAME',
                        passwordVariable: 'GIT_TOKEN'
                    ),
                       string(
                    credentialsId: 'email-creds',
                    variable: 'GIT_EMAIL'
                    )]) {              
                        sh """
                        set -e
                        git config user.name "$GIT_USERNAME"
                        git config user.email "$GIT_EMAIL"

                        git fetch origin
                        git checkout main
                        git reset --hard origin/main

                        sed -i "s|image:.*|image: ${IMAGE_NAME}:${IMAGE_TAG}|" main_branch_code/k8s/deployment.yaml

                        git add main_branch_code/k8s-80/deployment.yaml
                        git diff --cached --quiet || git commit -m "Updated image to ${IMAGE_TAG}"
                        git push https://${GIT_USERNAME}:${GIT_TOKEN}@github.com/$GIT_USERNAME/multibranch_pipeline_ecommerce.git main
                        """
                    }
                }
            }
        }
    }
  post {
    always {
        script {
            echo "========== EMAIL NOTIFICATION START =========="
            echo "Build Status: ${currentBuild.currentResult}"
            echo "Job Name: ${env.JOB_NAME}"
            echo "Build Number: ${env.BUILD_NUMBER}"
            echo "Build URL: ${env.BUILD_URL}"

            emailext(
                subject: "Pipeline ${currentBuild.currentResult}: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: """
                    <h2>Jenkins CI/CD Pipeline Status</h2>

                    <p><b>Project:</b> ${env.JOB_NAME}</p>
                    <p><b>Build Number:</b> ${env.BUILD_NUMBER}</p>
                    <p><b>Status:</b> ${currentBuild.currentResult}</p>

                    <p>
                        <b>Build URL:</b>
                        <a href="${env.BUILD_URL}">
                            ${env.BUILD_URL}
                        </a>
                    </p>
                """,
                to: 'chetan.singh673@gmail.com,chetan.pokhariya93@gmail.com',
                mimeType: 'text/html'
            )

            echo "========== EMAIL NOTIFICATION END =========="
        }
     }
  }
}
